// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Report.Persistence.Data;

#nullable disable

namespace Report.Persistence.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260218155144_Reporttt")]
    partial class Reporttt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Report")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Report.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NotifiedDepartmantId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReportStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportTopicId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReportingUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReportStatusId");

                    b.HasIndex("ReportTopicId");

                    b.HasIndex("ReportingUserId");

                    b.ToTable("Reports", "Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportStatuses", "Report");
                });

            modelBuilder.Entity("Report.Domain.Entities.ReportTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ReportTopics", "Report");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TopicName = "Hata Bildirimi"
                        },
                        new
                        {
                            Id = 2,
                            TopicName = "Geri Bildirim"
                        },
                        new
                        {
                            Id = 3,
                            TopicName = "Diğer"
                        });
                });

            modelBuilder.Entity("Report.Domain.Entities.Report", b =>
                {
                    b.HasOne("Report.Domain.Entities.ReportStatus", "ReportStatus")
                        .WithMany()
                        .HasForeignKey("ReportStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Report.Domain.Entities.ReportTopic", "ReportTopic")
                        .WithMany()
                        .HasForeignKey("ReportTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportStatus");

                    b.Navigation("ReportTopic");
                });
#pragma warning restore 612, 618
        }
    }
}
