// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlow.Persistence.ApplicationContext;

#nullable disable

namespace TaskFlow.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskFlow.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPlanId");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.CompanyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("companiesPlan");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("messages");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.PlanProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyPlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDailyPlannerEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeadlineNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeAddTaskNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeGroupChat")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeTaskPriorityCategory")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeVideoCall")
                        .HasColumnType("boolean");

                    b.Property<int>("PeopleAddedLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TeamLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPlanId")
                        .IsUnique();

                    b.ToTable("planProperties");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeadlineTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TaskPriorityCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskStatusId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskPriorityCategoryId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("tasks");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.TaskAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId1");

                    b.ToTable("taskAnswers");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.TaskPriorityCategory", b =>
                {
                    b.Property<Guid>("TaskPriorityCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskPriorityCategoryId");

                    b.ToTable("taskPriorityCategories");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.TaskStatus", b =>
                {
                    b.Property<Guid>("TaskStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskStatusId");

                    b.ToTable("taskStatuses");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Company", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.CompanyPlan", "CompanyPlan")
                        .WithMany()
                        .HasForeignKey("CompanyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPlan");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.PlanProperties", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.CompanyPlan", "CompanyPlan")
                        .WithOne("PlanProperties")
                        .HasForeignKey("TaskFlow.Domain.Entities.PlanProperties", "CompanyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPlan");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.TaskPriorityCategory", "TaskPriority")
                        .WithMany()
                        .HasForeignKey("TaskPriorityCategoryId");

                    b.HasOne("TaskFlow.Domain.Entities.TaskStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.TaskAnswer", b =>
                {
                    b.HasOne("TaskFlow.Domain.Entities.Task", "Task")
                        .WithMany("TaskAnswer")
                        .HasForeignKey("TaskId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.CompanyPlan", b =>
                {
                    b.Navigation("PlanProperties")
                        .IsRequired();
                });

            modelBuilder.Entity("TaskFlow.Domain.Entities.Task", b =>
                {
                    b.Navigation("TaskAnswer");
                });
#pragma warning restore 612, 618
        }
    }
}
