// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tenant.Infrastructure.Data.TenantDb;

#nullable disable

namespace Tenant.Infrastructure.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    partial class TenantDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tenant")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tenant.Domain.Entities.CompanyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanPrice")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PlanPropertiesId");

                    b.ToTable("companyPlans", "Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.PlanProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDailyPlannerEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeadlineNotificationEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeAddTaskNotifications")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIncludeTaskPriorityCategory")
                        .HasColumnType("boolean");

                    b.Property<int>("PeopleAddedLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TeamLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("planProperties", "Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.CompanyPlan", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.PlanProperties", "PlanProperties")
                        .WithMany()
                        .HasForeignKey("PlanPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
