// <auto-generated />
using Identity.Persistence.Data.IdentityDb;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Identity.Persistence.Migrations
{
    [DbContext(typeof(IdentityManagementDbContext))]
    [Migration("20260319000000_AddGroupEvents")]
    partial class AddGroupEvents
    {
    }
}
