// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectManagement.Persistence.Data.ProjectManagementDb;

#nullable disable

namespace ProjectManagement.Persistence.Migrations
{
    [DbContext(typeof(ProjectManagementDbContext))]
    [Migration("20260205184239_Initial_ProjectManagement")]
    partial class Initial_ProjectManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ProjectManagement")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectManagement.Domain.Entities.SubTaskAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubtaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubtaskId");

                    b.ToTable("SubTaskAnswers", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Subtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("integer");

                    b.Property<string>("TaskTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("Subtasks", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DeadlineTime")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TaskPriorityCategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("DeadlineTime");

                    b.HasIndex("TaskPriorityCategoryId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("Tasks", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TaskAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("SenderId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskAnswers", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TaskPriorityCategory", b =>
                {
                    b.Property<int>("TaskPriorityCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskPriorityCategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskPriorityCategoryId");

                    b.ToTable("TaskPriorityCategories", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TaskStatusId");

                    b.ToTable("TaskStatuses", "ProjectManagement");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.SubTaskAnswer", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Subtask", null)
                        .WithMany("subTaskAnswers")
                        .HasForeignKey("SubtaskId");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Subtask", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Task", "Task")
                        .WithMany("subtask")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectManagement.Domain.Entities.TaskStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Task", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.TaskPriorityCategory", "TaskPriority")
                        .WithMany()
                        .HasForeignKey("TaskPriorityCategoryId");

                    b.HasOne("ProjectManagement.Domain.Entities.TaskStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.TaskAnswer", b =>
                {
                    b.HasOne("ProjectManagement.Domain.Entities.Task", null)
                        .WithMany("taskAnswers")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Subtask", b =>
                {
                    b.Navigation("subTaskAnswers");
                });

            modelBuilder.Entity("ProjectManagement.Domain.Entities.Task", b =>
                {
                    b.Navigation("subtask");

                    b.Navigation("taskAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
