// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tenant.Persistence.Data.TenantDb;

#nullable disable

namespace Tenant.Persistence.Migrations
{
    [DbContext(typeof(TenantDbContext))]
    [Migration("20260219073855_Tntlss")]
    partial class Tntlss
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Tenant")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tenant.Domain.Entities.CompanyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlanPrice")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanPropertiesId")
                        .HasColumnType("uuid");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PlanPropertiesId");

                    b.ToTable("companyPlans", "Tenant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018da123-abcd-7000-9000-000000000001"),
                            PlanName = "Start-up",
                            PlanPrice = 0,
                            PlanPropertiesId = new Guid("018da123-4567-7000-8000-000000000001"),
                            isActive = true
                        },
                        new
                        {
                            Id = new Guid("018da123-abcd-7000-9000-000000000002"),
                            PlanName = "Business",
                            PlanPrice = 499,
                            PlanPropertiesId = new Guid("018da123-4567-7000-8000-000000000002"),
                            isActive = true
                        },
                        new
                        {
                            Id = new Guid("018da123-abcd-7000-9000-000000000003"),
                            PlanName = "Enterprise",
                            PlanPrice = 1499,
                            PlanPropertiesId = new Guid("018da123-4567-7000-8000-000000000003"),
                            isActive = true
                        });
                });

            modelBuilder.Entity("Tenant.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("text");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantSubscriptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("paymentTransactions", "Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.PlanProperties", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("IndividualTaskLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("IsInternalReportingEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("PeopleAddedLimit")
                        .HasColumnType("integer");

                    b.Property<int>("TeamLimit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("planProperties", "Tenant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("018da123-4567-7000-8000-000000000001"),
                            IndividualTaskLimit = 100,
                            IsInternalReportingEnabled = false,
                            PeopleAddedLimit = 5,
                            TeamLimit = 1
                        },
                        new
                        {
                            Id = new Guid("018da123-4567-7000-8000-000000000002"),
                            IndividualTaskLimit = 1000,
                            IsInternalReportingEnabled = false,
                            PeopleAddedLimit = 25,
                            TeamLimit = 5
                        },
                        new
                        {
                            Id = new Guid("018da123-4567-7000-8000-000000000003"),
                            IndividualTaskLimit = 10000,
                            IsInternalReportingEnabled = true,
                            PeopleAddedLimit = 1000,
                            TeamLimit = 50
                        });
                });

            modelBuilder.Entity("Tenant.Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CanceledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentProviderSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantUsageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPlanId");

                    b.HasIndex("TenantUsageId")
                        .IsUnique();

                    b.ToTable("tenantSubscriptions", "Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.TenantUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentGroupCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentIndividualTaskCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentTaskCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentUserCount")
                        .HasColumnType("integer");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("tenantUsages", "Tenant");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.CompanyPlan", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.PlanProperties", "PlanProperties")
                        .WithMany()
                        .HasForeignKey("PlanPropertiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanProperties");
                });

            modelBuilder.Entity("Tenant.Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("Tenant.Domain.Entities.CompanyPlan", "CompanyPlan")
                        .WithMany()
                        .HasForeignKey("CompanyPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tenant.Domain.Entities.TenantUsage", "TenantUsage")
                        .WithOne()
                        .HasForeignKey("Tenant.Domain.Entities.TenantSubscription", "TenantUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyPlan");

                    b.Navigation("TenantUsage");
                });
#pragma warning restore 612, 618
        }
    }
}
