// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stats.Persistence.Data;

#nullable disable

namespace Stats.Persistence.Migrations
{
    [DbContext(typeof(StatsDbContext))]
    partial class StatsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Stats")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stats.Domain.Entities.WorkerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("OverdueIncompleteTasksCount")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date");

                    b.Property<int>("TasksCompletedBeforeDeadline")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTasksAssigned")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Period")
                        .IsUnique();

                    b.ToTable("UserStats", "Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
